table 'Measures (2)'
	lineageTag: f1d4d9d4-ec79-4e18-a695-03ac694aeafb

	measure 'Sales vs Last Month Sales' =
			
			[total sales] - [last month sales]
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 0118e2bd-b93e-4d23-821d-4c90396e3e89

	measure 'last month sales' =
			
			CALCULATE(
			    [total sales],
			    DATEADD('Calendar'[Date],-1,MONTH)
			 )
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: c7afdcce-83c6-4793-b211-c061c3a8eed0

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'total sales' =
			
			SUM(coffee_shop_sales[sales])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: ed296a63-de74-490a-abcb-2f89a9e8675b

	measure '% MOM' =
			
			DIVIDE(
			    [Sales vs Last Month Sales],
			    [last month sales]
			)
		formatString: 0%;-0%;0%
		lineageTag: 76b31cba-67b9-468a-941f-aee1820319e5

	partition 'Measures (2)' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}}),
				    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

